<div id="containerone" class="category-products jcarousel-skin-tango scroller">
<?php
	$cObj = Mage::getModel('catalog/category')->load(3);	
	$productObj = $cObj->getProductCollection()->getData();
    $_helper = $this->helper('catalog/output');

?>


    <?php if($this->getMode()!='grid'): ?>

    <?php $_iterator = 0; ?>

    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    <?php else: ?>

  <ul id="mycarouselfeatured" class="products-scroller">

    <?php $i=1;foreach($productObj as $_productData): ?>
	
		
        <?php 	$_product = Mage::getModel('catalog/product')->load($_productData['entity_id']); ?>

            <li class="item<?php echo (($i%2==0)?"first":"last")?> capslide_img_cont4">
            <div class="outer">

		 <?php $i++; ?>
         <h2 class="product-name ic_text"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(148,146); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                 <a rel="example_group" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false); ?>" class="zoom-image"></a>
                <div class="ic_caption">
				
                <?php echo $this->getPriceHtml($_product, true, '-righthome') ?>

                <div class="actions">

                    <?php if($_product->isSaleable()): ?>

                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Shop now') ?></span></span></button>

                    <?php else: ?>

                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>

                    <?php endif; ?>

                </div>
                </div>
			</div>
            </li>

        <?php endforeach ?>

   </ul>

        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

    <?php endif; ?>

</div>



